### ISSUE TITLE
Loading a save state causes textures to disappear

### ISSUE THREAD

**Issue by ianlazerbeem** [azahar-emu/azahar#1280]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Affected Build(s)

Azahar 2122

### Description of Issue

I am playing fire emblem fates on azahar 2122 with the hd texture pack on and I saved state, but loading state causes the ground textures to disappear. the sprites and everything on the bottom screen remained normal. going into combat looks fine, and after combat the map looks fine too. Whether I make the state with custom textures on or off, and whether i load it with them on or off, this occurs.

### Expected Behavior

The state would load and the textures of the ground would be visible. Typically on Azahar's predecessor Citra loading a state would disable custom textures, but not make textures disappear entirely.

### Reproduction Steps

Save State in a battle in Fire Emblem Fates
Load State

### Log File

[azahar_log.txt](https://github.com/user-attachments/files/21604086/azahar_log.txt)

### System Configuration

CPU: Intel(R)Core(TM) i7-0750H CPU @ 2.60GHz
GPU/Driver: Intel(R) UHD Graphics,
RAM: 16 GB
OS: Windows 10 Home 22H2 (build 19045.6093)

**Comment by username227** [comment]
I have what appears to be a similar issue on Dragon Quest VII. Loading a save state causes the background graphics to be black, and only the people are visible, making the game virtually unplayable and save states completely useless for this game. As above, this happens even though custom textures are disabled.

**Comment by ianlazerbeem** [comment]
> I have what appears to be a similar issue on Dragon Quest VII. Loading a save state causes the background graphics to be black, and only the people are visible, making the game virtually unplayable and save states completely useless for this game. As above, this happens even though custom textures are disabled.

Do you have custom textures in the custom textures folder, and have them disabled? That's the case on my end. Or is your custom textures folder empty?

**Comment by TheMetroid7998** [comment]
I believe I have the same issue in Kid Icarus Uprising. This only started happening like 15 minutes ago. Before that, savestates worked fine for dozens of separate save states.
As a note, save states made _before_ some catalyst point actually still load fine. New ones seem to replicate the issue.

<img width="1680" height="720" alt="Image" src="https://github.com/user-attachments/assets/1f25a7f9-3bb0-48b4-b57c-0cad34926486" />

Pertinent Info:
- Azahar Build/Version 2122.1
- Custom Textures: Off/None
- Graphics API: Vulkan
- System Specs: R7 7700X / RTX 4070 Super / 32GB DDR5 RAM / Windows 11 24H2 26100.4652

**Comment by username227** [comment]
> > I have what appears to be a similar issue on Dragon Quest VII. Loading a save state causes the background graphics to be black, and only the people are visible, making the game virtually unplayable and save states completely useless for this game. As above, this happens even though custom textures are disabled.
> 
> Do you have custom textures in the custom textures folder, and have them disabled? That's the case on my end. Or is your custom textures folder empty?

No, I don't have any custom textures; never played around with that. And yet the background  goes black when I load the save state (occasionally it simply dims without going all the way black).

**Comment by makemeunsee** [comment]
I have the same issue, in Zelda Majora's Mask, both when using or not using custom textures.

* Azahar Build/Version 2123
* Graphics API: OpenGL
* System: Geforce 980, Linux

I've just downgraded to 2121.2, and the issue isnt there, or at least it's not as bad:
* on one occasion, it all went to black, but I couldnt reproduce it
* if using custom textures, after every state load, default textures are used instead (until new textures need to be loaded and then the custom ones are used); not great but at least the game is still playable :)

I'll give a try at identifying the commit which introduces the regression.

**Comment by makemeunsee** [comment]
Identified to this commit: [`5e2161d`](https://github.com/azahar-emu/azahar/commit/5e2161d90b9b32b492937d8caadd9f83820b5bfa)  
(i.e. `bf587885c` is good, `5e2161d` has the issue).

How it looks (majora's mask intro, roughly 10s in after running the game):

after saving state, before reloading state:
<img width="575" height="665" alt="Image" src="https://github.com/user-attachments/assets/cf60f678-c376-4577-b34d-0bf2eb0dc4be" />

after loading state:
<img width="595" height="710" alt="Image" src="https://github.com/user-attachments/assets/b9177543-d1dc-4700-b36d-a7717a763779" />

Tested and confirmed on both OpenGL and Vulkan, no custom textures involved.

**Comment by TheMetroid7998** [comment]
> Identified to this commit: [`5e2161d`](https://github.com/azahar-emu/azahar/commit/5e2161d90b9b32b492937d8caadd9f83820b5bfa)  
> (i.e. `bf587885c` is good, `5e2161d` has the issue).
> ...
> Tested and confirmed on both OpenGL and Vulkan, no custom textures involved.

Just wanna say, major kudos for this. If you don't mind, how did you go about testing different versions? I'd like to help identify regressions like this when I can.

**Comment by makemeunsee** [comment]
> how did you go about testing different versions?

I built individual revisions from source, and tested them each. [`git bisect`](https://stackoverflow.com/questions/4713088/how-do-i-use-git-bisect) helps with the process.

I got a bit further and found an apparent fix, but I dont really understand what I'm doing, I never had a look at this project before.

That's the fix:
```diff
--- a/src/video_core/pica/pica_core.h
+++ b/src/video_core/pica/pica_core.h
@@ -252,6 +256,8 @@ public:
         friend class boost::serialization::access;
         template <class Archive>
         void serialize(Archive& ar, const u32 file_version) {
+            lut_dirty = true;
             ar& boost::serialization::make_binary_object(this, sizeof(Fog));
         }
     };
```

i.e. forcing the fog LUT (Look Up Table?) to be dirty when serializing it.

I would expect then that dirtying other LUTs is important too but from my testing it doesnt make a difference:

```diff
--- a/src/video_core/pica/pica_core.h
+++ b/src/video_core/pica/pica_core.h
@@ -184,6 +184,8 @@ public:
         friend class boost::serialization::access;
         template <class Archive>
         void serialize(Archive& ar, const u32 file_version) {
+            table_dirty = TableAllDirty;
             ar& boost::serialization::make_binary_object(this, sizeof(ProcTex));
         }
     };
@@ -224,6 +226,8 @@ public:
         friend class boost::serialization::access;
         template <class Archive>
         void serialize(Archive& ar, const u32 file_version) {
+            lut_dirty = LutAllDirty;
             ar& boost::serialization::make_binary_object(this, sizeof(Lighting));
         }
     };
```

I also tried to serialize `PicaCore::dirty_regs` and force it to 'all regs dirty', but if anything it made the fix less consistent.

I dont have the means to test this hack much further, nor enough understanding of the project to judge what makes sense or not. Let's wait for a maintainer to chime in.

**Comment by kainpatata-dev** [comment]
I have The same issue. I try to load suave states on Dragon Quest VII and Pokémon super mystery Dungeon. On pokemon, Dialogs boxes blink for a couple of seconds and then disappear for ever.

>  I have what appears to be a similar issue on Dragon Quest VII. Loading a save state causes the background graphics to be black, and only the people are visible, making the game virtually unplayable and save states completely useless for this game. As above, this happens even though custom textures are disabled.

On dragon quest happens what this user describes.
 
Azahar Build/Version: 2123
Custom Textures: Off/None
Graphics API: OpenGLES
System: Android

**Comment by Jorde5212** [comment]
Yeah I was on Azahar version 2123, Vulkan graphics, Windows 11. Similar issue of black textures on loading a save state in Fire Emblem Fates (in my case it was the map being entirely black, unit sprites were the only thing left). Downgrading to version 2121.2 fixed this issue entirely. There is still a small issue of my custom textures disappearing upon loading the save state, but that's easily fixed by turning them off and back on again with the hotkey.

Top one is an image of the issue, the bottom image is what it's supposed to look like.

<img width="1915" height="1029" alt="Image" src="https://github.com/user-attachments/assets/c749c2c1-85c6-4cb8-8c91-cd5fde5af4a3" />

<img width="1919" height="1028" alt="Image" src="https://github.com/user-attachments/assets/d9008c47-8151-4b53-8ad1-a8407870e564" />

**Comment by makemeunsee** [comment]
> There is still a small issue of my custom textures disappearing upon loading the save state

I had a look at that too, here's a possible fix, I could submit it as a PR actually:

```diff
--- a/src/core/core.cpp
+++ b/src/core/core.cpp
@@ -816,6 +816,11 @@ void System::serialize(Archive& ar, const unsigned int file_version) {

     // This needs to be set from somewhere - might as well be here!
     if (Archive::is_loading::value) {
+
+        if (Settings::values.custom_textures) {
+            custom_tex_manager->FindCustomTextures();
+        }
+
         u32 cheats_pid;
         ar & cheats_pid;
         timing->UnlockEventQueue();
```

**Comment by username227** [comment]
The problem doesn't seem to be related to custom textures. When the graphics disappear on my game (no use of custom textures) opening the graphics tab on the options menu resets the graphics.

**Comment by makemeunsee** [comment]
> When the graphics disappear on my game (no use of custom textures) opening the graphics tab on the options menu resets the graphics.

Interesting, that doesnt fix anything for me.

**Comment by TheMetroid7998** [comment]
> The problem doesn't seem to be related to custom textures. When the graphics disappear on my game (no use of custom textures) opening the graphics tab on the options menu resets the graphics.

I think people are saying this to prevent the otherwise inevitable "are you using custom textures" question that would seem to be the easy source of the problem. The graphics tab thing doesn't fix it for me either, nor does toggling custom textures, etc.

**Comment by Jorde5212** [comment]
Yeah people are getting confused on two separate bugs. There's a custom textures bug on loading a save state which is easily fixed by toggling them off and back on again with F7. It'd be nice to have fixed, but it's not gamebreaking. The bug this post is about is most of a game's textures becoming black upon loading a save state, making save states basically unuseable for many games in the most recent update. Reverting to Azahar version 2121.2 fixes this issue's titular bug, for those looking for a fix (thanks to Makemeunsee for that one).

I'm unsure how simply opening the graphics tab would fix it. For me, the black textures bug was persisent on opengl or vulkan, and all manner of graphics settings being changed on my end. Only downgrading to the amentioned version fixed it.

**Comment by TheMetroid7998** [comment]
> Yeah people are getting confused on two separate bugs. There's a custom textures bug on loading a save state which is easily fixed by toggling them off and back on again with F7. It'd be nice to have fixed, but it's not gamebreaking. The bug this post is about is most of a game's textures becoming black upon loading a save state, making save states basically unuseable for many games in the most recent update. Reverting to Azahar version 2121.2 fixes this issue's titular bug, for those looking for a fix (thanks to Makemeunsee for that one).
> 
> I'm unsure how simply opening the graphics tab would fix it. For me, the black textures bug was persisent on opengl or vulkan, and all manner of graphics settings being changed on my end. Only downgrading to the amentioned version fixed it.

ohhh okay. I haven't experienced the custom texture bug yet, just the black textures one for savestates. I might consider downgrading for now to continue my playthrough.

**Comment by SimplyTadpole** [comment]
Think this issue could be related to [#762](https://github.com/azahar-emu/azahar/issues/762)? I've been waiting for that bug to be fixed for a long time now.

**Comment by kainpatata-dev** [comment]
> Think this issue could be related to [#762](https://github.com/azahar-emu/azahar/issues/762)? I've been waiting for that bug to be fixed for a long time now.

I think It may be the same issue. Looking the screenshot in that issue, My problema is more similar to the Digimon screenshot.

**Comment by dammitjim** [comment]
Also experiencing this issue it’s making save states unusable unfortunately

**Comment by lixiansen4357** [comment]
I can confirm that this texture corruption bug when loading save states is still present in the **latest Azahar 2123.3**.

**Specific Behavior Observed:**
In games like Fire Emblem if and Fire Emblem Echoes: Shadows of Valentia, after performing a quick save and then loading that state, the game's textures become glitched. This frequently manifests as missing background textures.

**Key Details:**

- The issue occurs consistently regardless of the graphics backend (both OpenGL and Vulkan).
- It is independent of the "Custom Textures" setting (enabled or disabled).
- There is a notable observation: occasionally, the textures appear to load correctly for exactly the first frame after loading the state, but are instantly refreshed/corrupted in the next moment. This might be a crucial clue for debugging.

This makes the quick save/load feature practically unusable in the current version. Rolling back to 2121.2 remains the only workaround for now.

**Comment by piefish1996** [comment]
I've had this same /similar issue playing the Mario & Luigi games (Superstar Saga, Bowser's Inside Story and Paper Jam).  When you load a save state Mario and Luigi will just disappear, whether it's in battle, in the overworld or even on the menu screens. For Paper Jam oddly enough, Paper Mario won't disappear, only regular Mario and Luigi.

**Comment by ArjunSindhya** [comment]
Any security concerns if I stay on 2121.2? Quick saves are quite important to me.

**Comment by TheMetroid7998** [comment]
> That's the fix:
```
--- a/src/video_core/pica/pica_core.h
+++ b/src/video_core/pica/pica_core.h
@@ -252,6 +256,8 @@ public:
         friend class boost::serialization::access;
         template <class Archive>
         void serialize(Archive& ar, const u32 file_version) {
+            lut_dirty = true;
             ar& boost::serialization::make_binary_object(this, sizeof(Fog));
         }
     };
--- a/src/video_core/pica/pica_core.h
+++ b/src/video_core/pica/pica_core.h
@@ -184,6 +184,8 @@ public:
         friend class boost::serialization::access;
         template <class Archive>
         void serialize(Archive& ar, const u32 file_version) {
+            table_dirty = TableAllDirty;
             ar& boost::serialization::make_binary_object(this, sizeof(ProcTex));
         }
     };
@@ -224,6 +226,8 @@ public:
         friend class boost::serialization::access;
         template <class Archive>
         void serialize(Archive& ar, const u32 file_version) {
+            lut_dirty = LutAllDirty;
             ar& boost::serialization::make_binary_object(this, sizeof(Lighting));
         }
     };
```

The 2124 release still has this issue -- I tried adding your fix to it and rebuilding and it doesn't seem to work as effectively / at all anymore. I'm no expert so who knows what's been changed since you came up with this. It was worth a shot at least.

**Comment by PabloMK7** [comment]
Hello, can someone affected by this issue try the artifacts from this pull request? https://github.com/azahar-emu/azahar/actions/runs/21253331883

It should fix both issues of graphical glitches and custom textures not loading after restoring a save state.

**Comment by TheMetroid7998** [comment]
> It should fix both issues of graphical glitches and custom textures not loading after restoring a save state.

I only had time to try this with Kid Icarus Uprising, but I did not see any graphical issues, even when loading save states made in previous versions of Azahar. (I technically tested Ocarina of Time 3D as well, but there were issues with my texture pack and I don't want to confirm new glitches without checking the pack first. The textures did load though.) From my testing, your fix works!

**Comment by xombium** [comment]
so how do i fix this?

**Comment by TheMetroid7998** [comment]
> so how do i fix this?

Wait until the next version of Azahar is released or install the version @PabloMK7 built and shared with us in their previous comment.

**Comment by dammitjim** [comment]
Thank you @PabloMK7 for your work on this!

**Comment by dannymize93-ops** [comment]
Had the same missing texture issue when loading save state in Omega Ruby - tested the windows-msvc artifact posted above & save state loads without missing textures now. Thank you!

**Comment by Zoran501** [comment]
Ground textures in Fire Emblem Fates still disappear upon loading a save state in Azahar 2124.2 on Mac

**Comment by roncocn** [comment]
In Ocarina of Time, after loading a savestate, the screen goes black and sometimes green, or yellow in Azahar 2124.2 on an android device : AYN THOR

**Comment by ReaTsukuda** [comment]
The above fix doesn't seem to have done anything for the Etrian Odyssey games. I haven't tested all of them, but both EO2U and EO5 exhibit the same problems upon loading a save state: character graphics in town disappear, all 3D level geometry disappears while in the labyrinth, and the background fog disappears when in a battle. The battle fog issue seems to fix itself after several seconds, the town and labyrinth issues take much longer.

The Vulkan and OpenGL renderers both have this problem. I'm currently using Linux, but this same issue occurred with previous versions of Azahar when I was using Windows.

Town issue (there should be a character on the right side of the screen): 
<img width="400" height="561" alt="Image" src="https://github.com/user-attachments/assets/9d58e316-60fc-437f-9ce3-92c752fbbb45" />

Labyrinth issue (all geometry is missing): 
<img width="400" height="561" alt="Image" src="https://github.com/user-attachments/assets/c9bae363-dadc-405b-88db-414b07eb3158" />

Battle issue (fog is missing, screenshot with the fog provided for comparison):
<img width="400" height="561" alt="Image" src="https://github.com/user-attachments/assets/9833d803-f0c8-4937-b294-eaa3b13e29ec" />
<img width="400" height="561" alt="Image" src="https://github.com/user-attachments/assets/f7a79d87-5809-4032-b1f7-df7c84efc807" />

**Comment by jhtheman99** [comment]
Just in case anyone finds this thread in the future, I'm on version 2124.3 and I'm getting the background texture blackout bug after loading a save state on FE Fates. All I need to do to resolve the issue is enter a combat and view the animation (either turn on animations or just hold down the L button while starting the combat)

**Comment by TheAxolotl-gh** [comment]
> Hello, can someone affected by this issue try the artifacts from this pull request? https://github.com/azahar-emu/azahar/actions/runs/21253331883
> 
> It should fix both issues of graphical glitches and custom textures not loading after restoring a save state.

Keeping this version installed on Android does fix the issue on EO5
